Repository MediaMarktSaturn/technolinator, pull requests merged in 2023-10, with the labels that each got.

#195 chore(deps): update dependency @cyclonedx/cdxgen to v9.8.5
  .github/workflows/ci.yml
Labels: dependencies, renovate

#196 chore(deps): update dependency interlynk-io/sbomqs to v0.0.21
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#202 chore(deps): update dependency interlynk-io/sbomqs to v0.0.22
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#203 chore(deps): update dependency @cyclonedx/cdxgen to v9.8.8
  .github/workflows/ci.yml
Labels: dependencies, renovate

#204 chore(deps): update dependency anchore/grype to v0.70.0
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#205 chore(deps): update dependency @cyclonedx/cdxgen to v9.8.9
  .github/workflows/ci.yml
Labels: dependencies, renovate

#206 chore(deps): update dependency interlynk-io/sbomqs to v0.0.23
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#207 chore(deps): update dependency anchore/grype to v0.71.0
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#209 feat(jvm): Update to Java 21
  .github/workflows/ci.yml
  .github/workflows/verify.yml
  .mvn/jvm.config
  pom.xml
  src/main/docker/Dockerfile
  src/test/docker/structure-test.yaml
  src/test/resources/repo/maven-wrapper/.mvn/wrapper/MavenWrapperDownloader.java
  src/test/resources/repo/maven-wrapper/.mvn/wrapper/maven-wrapper.properties
  src/test/resources/repo/maven-wrapper/mvnw
  src/test/resources/repo/maven-wrapper/mvnw.cmd
Labels: enhancement, dependencies

#210 chore(deps): update dependency @cyclonedx/cdxgen to v9.8.10
  .github/workflows/ci.yml
Labels: dependencies, renovate

#213 chore(deps): update dependency anchore/grype to v0.72.0
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#214 chore(deps): update dependency @cyclonedx/cdxgen to v9.9.0
  .github/workflows/ci.yml
Labels: dependencies, renovate

#220 ci(actions): add concurrency to ci workflow
  .github/workflows/ci.yml
Labels: github_actions

#219 ci(actions): skip ci on main for dependabot merges
  .github/workflows/ci.yml
Labels: github_actions

#223 chore(deps): update dependency interlynk-io/sbomqs to v0.0.24
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate
