Repository MediaMarktSaturn/technolinator, pull requests merged in 2023-09, with the labels that each got.

#171 chore(deps): update dependency anchore/grype to v0.66.0
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#165 chore(deps): update dependency @cyclonedx/cdxgen to v9.7.0
  .github/workflows/ci.yml
Labels: dependencies, renovate

#174 chore(deps): update dependency @cyclonedx/cdxgen to v9.7.1
  .github/workflows/ci.yml
Labels: dependencies, renovate

#177 chore(deps): update dependency @cyclonedx/cdxgen to v9.7.3
  .github/workflows/ci.yml
Labels: dependencies, renovate

#184 chore(deps): update dependency anchore/grype to v0.68.0
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#186 chore(deps): update dependency anchore/grype to v0.68.1
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#188 chore(deps): update dependency anchore/grype to v0.69.0
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#189 ci(actions): adjust release creation
  .github/workflows/ci.yml
  .releaserc
Labels: github_actions

#192 fix(actions): fix CI on release creation
  .github/workflows/ci.yml
Labels: bug

#193 chore(deps): update dependency @cyclonedx/cdxgen to v9.8.4
  .github/workflows/ci.yml
Labels: dependencies, renovate

#194 chore(deps): update dependency anchore/grype to v0.69.1
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate
