Repository MediaMarktSaturn/technolinator, pull requests merged in 2024-01, with the labels that each got.

#293 chore(deps): update dependency owasp-dep-scan/dep-scan to v5.1.4
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#292 chore(deps): update dependency @cyclonedx/cdxgen to v9.10.2
  .github/workflows/ci.yml
Labels: dependencies, renovate

#294 chore(deps): update dependency owasp-dep-scan/dep-scan to v5.1.5
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#295 chore(deps): update dependency anchore/grype to v0.74.0
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#296 chore(deps): update dependency interlynk-io/sbomqs to v0.0.29
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#300 chore(deps): update dependency owasp-dep-scan/dep-scan to v5.1.8
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#308 ci(actions): add workflow to comment on opened issue
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/workflows/assign_issue.yml
Labels: github_actions

#310 chore(deps): update dependency @cyclonedx/cdxgen to v9.11.0
  .github/workflows/ci.yml
Labels: dependencies, renovate

#309 feat: make commit status update configurable
  src/main/java/com/mediamarktsaturn/technolinator/events/DispatcherBase.java
  src/main/resources/application.properties
  src/test/java/com/mediamarktsaturn/technolinator/CustomTestProfiles.java
  src/test/java/com/mediamarktsaturn/technolinator/events/OnPushDispatcherTest.java
  src/test/java/com/mediamarktsaturn/technolinator/events/OnPushDispatcherWithDisabledCommitStatusWriteTest.java
Labels: enhancement

#312 docs: add APP_COMMIT_STATUS_WRITE_ENABLED
  docs/Runtime_Config.md
Labels: documentation

#311 test: fix flaky successful upload test case
  src/test/java/com/mediamarktsaturn/technolinator/sbom/DependencyTrackClientTest.java
Labels: bug

#313 ci(actions): close dependabot pull requests for src/test
  .github/workflows/close_dependabot_pr.yaml
Labels: github_actions

#314 chore(deps): update dependency @cyclonedx/cdxgen to v9.11.1
  .github/workflows/ci.yml
Labels: dependencies, renovate

#315 chore(deps): update dependency owasp-dep-scan/dep-scan to v5.2.0
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#319 chore(deps): update dependency anchore/grype to v0.74.1
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#322 chore(deps): update dependency anchore/grype to v0.74.2
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#324 chore(deps): update dependency @cyclonedx/cdxgen to v9.11.2
  .github/workflows/ci.yml
Labels: dependencies, renovate

#325 chore(deps): update dependency owasp-dep-scan/dep-scan to v5.2.1
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#329 chore(deps): update dependency owasp-dep-scan/dep-scan to v5.2.2
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#331 ci(actions): skip ci for non relevant changes
  .github/workflows/ci.yml
Labels: github_actions

#330 docs(readme): adjust latest release badge
  README.md
Labels: documentation

#333 chore(deps): update dependency @cyclonedx/cdxgen to v9.11.3
  .github/workflows/ci.yml
Labels: dependencies, renovate

#334 chore(deps): update dependency anchore/grype to v0.74.3
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#335 chore(deps): update dependency owasp-dep-scan/dep-scan to v5.2.3
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#336 chore(deps): update dependency interlynk-io/sbomqs to v0.0.30
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#340 chore(deps): update dependency @cyclonedx/cdxgen to v10
  .github/workflows/ci.yml
Labels: dependencies, renovate

#341 chore(deps): update dependency @cyclonedx/cdxgen to v10.0.1
  .github/workflows/ci.yml
Labels: dependencies, renovate

#342 chore(deps): update dependency @cyclonedx/cdxgen-plugins-bin to v1.5.5
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#343 chore(deps): update dependency owasp-dep-scan/dep-scan to v5.2.5
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate
