Repository MediaMarktSaturn/technolinator, pull requests merged in 2024-03, with the labels that each got.

#380 chore(deps): update dependency @cyclonedx/cdxgen to v10.2.1
  .github/workflows/ci.yml
Labels: dependencies, renovate

#382 chore(deps): update dependency apple/swift to v5.10
  .github/workflows/ci.yml
Labels: dependencies, renovate

#379 ci(actions): adjust workflow triggers
  .github/workflows/ci.yml
Labels: bug

#377 feat: add formulation support and update documentation
  docs/Deployment_Config.md
  docs/Repository_Config.md
  docs/Runtime_Config.md
  docs/docker-compose/docker-compose.sample.yml
  docs/docker-compose/sample.env
  src/main/java/com/mediamarktsaturn/technolinator/git/TechnolinatorConfig.java
  src/main/java/com/mediamarktsaturn/technolinator/sbom/CdxgenClient.java
  src/main/resources/application.properties
  src/test/java/com/mediamarktsaturn/technolinator/events/OnPushDispatcherTest.java
  src/test/java/com/mediamarktsaturn/technolinator/git/TechnolinatorConfigTest.java
  src/test/java/com/mediamarktsaturn/technolinator/sbom/CdxgenClientAnalysisLocationTest.java
  src/test/java/com/mediamarktsaturn/technolinator/sbom/CdxgenClientCommandCreationTest.java
  src/test/java/com/mediamarktsaturn/technolinator/sbom/CdxgenClientGenerationTest.java
  src/test/resources/configs/full_blown.yml
Labels: documentation, enhancement

#384 chore(deps): update dependency @cyclonedx/cdxgen to v10.2.2
  .github/workflows/ci.yml
Labels: dependencies, renovate

#387 ci(actions): adjust build trigger check for dependabot
  .github/workflows/ci.yml
Labels: bug, github_actions

#389 chore(deps): update dependency @cyclonedx/cdxgen to v10.2.3
  .github/workflows/ci.yml
Labels: dependencies, renovate

#390 chore(deps): update dependency owasp-dep-scan/dep-scan to v5.2.12
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#400 test: adjust RepositoryServiceTest.testInvalidBranch
  .github/workflows/ci.yml
  src/test/java/com/mediamarktsaturn/technolinator/git/RepositoryServiceTest.java
Labels: bug

#401 chore(deps): update dependency @cyclonedx/cdxgen to v10.2.4
  .github/workflows/ci.yml
Labels: dependencies, renovate

#410 chore(deps): update dependency owasp-dep-scan/dep-scan to v5.2.13
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#409 chore(deps): update dependency @cyclonedx/cdxgen to v10.2.5
  .github/workflows/ci.yml
Labels: dependencies, renovate

#414 chore(deps): update dependency owasp-dep-scan/dep-scan to v5.2.14
  .github/workflows/ci.yml
  .github/workflows/verify.yml
Labels: dependencies, renovate

#413 chore(deps): update dependency @cyclonedx/cdxgen to v10.2.6
  .github/workflows/ci.yml
Labels: dependencies, renovate
